import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// Rose palette: a charcoal header, rose-red actions and a light grey page
/// with white cards. Rose marks the one main action on a screen, the
/// selected tab and key highlights; everything else stays neutral. The
/// status hues only ever signal state (free/paid, pending, overdue) and are
/// always paired with a word or icon, since rose and danger sit close.
class AppColors {
  AppColors._();

  /// Charcoal: app bars, hero bands and primary text.
  static const Color ink = Color(0xFF333545);
  static const Color inkSoft = Color(0xFF454759);
  static const Color muted = Color(0xFF6B6D7A);
  static const Color subtle = Color(0xFF9A9CA8);
  static const Color border = Color(0xFFE5E5E8);
  static const Color fill = Color(0xFFF2F2F5);

  /// Strong neutral for outlines, disabled fills and chart tracks.
  static const Color line = Color(0xFFD6D6DC);
  static const Color canvas = Color(0xFFF5F5F5);
  static const Color surface = Color(0xFFFFFFFF);

  /// Brand rose: the main action, selected states and key highlights.
  static const Color brand = Color(0xFFF84464);
  static const Color brandPressed = Color(0xFFE0304F);
  static const Color brandSoft = Color(0xFFFFE8ED);

  /// Rose dark enough for small text on white or on [brandSoft].
  static const Color brandText = Color(0xFFC0183A);

  /// The launcher icon tile, the native splash and the launch animation are
  /// all [brand]; android/app/src/main/res/values/colors.xml mirrors it, and
  /// the icon bitmaps are regenerated by tool/brand_assets_test.dart.

  /// Text-safe status tones (4.5:1 on white) ...
  static const Color success = Color(0xFF0F7A55);
  static const Color warning = Color(0xFF9A5A00);
  static const Color danger = Color(0xFFD93636);

  /// ... their bright fills for dots, bars and outlines ...
  static const Color successBright = Color(0xFF2DC492);
  static const Color warningBright = Color(0xFFF5A623);

  /// ... and their soft backgrounds.
  static const Color successSoft = Color(0xFFE3F8F0);
  static const Color warningSoft = Color(0xFFFFF4E0);
  static const Color dangerSoft = Color(0xFFFDECEC);

  /// "Live" indicator dot, used on charcoal surfaces.
  static const Color live = successBright;
}

class AppShadows {
  AppShadows._();

  static List<BoxShadow> get soft => [
        BoxShadow(
          color: AppColors.ink.withValues(alpha: .08),
          blurRadius: 6,
          offset: const Offset(0, 1),
        ),
      ];

  static List<BoxShadow> get lifted => [
        BoxShadow(
          color: AppColors.ink.withValues(alpha: .18),
          blurRadius: 24,
          offset: const Offset(0, 10),
        ),
      ];
}

/// Single source of truth for the app's visual language.
class AppTheme {
  AppTheme._();

  static const String fontFamily = 'Inter';

  static const SystemUiOverlayStyle lightChrome = SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark,
    statusBarBrightness: Brightness.light,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
    systemNavigationBarContrastEnforced: false,
  );

  static const SystemUiOverlayStyle darkChrome = SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness: Brightness.dark,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarIconBrightness: Brightness.dark,
    systemNavigationBarContrastEnforced: false,
  );

  static const _radius = BorderRadius.all(Radius.circular(8));

  static ThemeData light() {
    const scheme = ColorScheme.light(
      primary: AppColors.brand,
      onPrimary: Colors.white,
      primaryContainer: AppColors.brandSoft,
      onPrimaryContainer: AppColors.brandText,
      secondary: AppColors.ink,
      onSecondary: Colors.white,
      secondaryContainer: AppColors.fill,
      onSecondaryContainer: AppColors.ink,
      tertiary: AppColors.success,
      onTertiary: Colors.white,
      error: AppColors.danger,
      onError: Colors.white,
      surface: AppColors.surface,
      onSurface: AppColors.ink,
      onSurfaceVariant: AppColors.muted,
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: Color(0xFFFAFAFA),
      surfaceContainer: AppColors.fill,
      surfaceContainerHigh: Color(0xFFEDEDF0),
      surfaceContainerHighest: Color(0xFFE8E8EC),
      outline: AppColors.border,
      outlineVariant: AppColors.border,
      inverseSurface: AppColors.ink,
      onInverseSurface: Colors.white,
      surfaceTint: Colors.transparent,
    );

    const buttonText = TextStyle(
      fontFamily: fontFamily,
      fontSize: 15,
      fontWeight: FontWeight.w700,
      letterSpacing: -.1,
    );

    return ThemeData(
      useMaterial3: true,
      colorScheme: scheme,
      fontFamily: fontFamily,
      scaffoldBackgroundColor: AppColors.canvas,
      splashFactory: InkSparkle.splashFactory,
      textTheme: const TextTheme(
        // Tuned for Inter: tight tracking on large bold type, near-neutral
        // at body sizes where Inter is already spaced for screens.
        displaySmall: TextStyle(
            fontSize: 30,
            height: 1.12,
            fontWeight: FontWeight.w800,
            letterSpacing: -1,
            color: AppColors.ink),
        headlineLarge: TextStyle(
            fontSize: 26,
            height: 1.15,
            fontWeight: FontWeight.w800,
            letterSpacing: -.8,
            color: AppColors.ink),
        headlineMedium: TextStyle(
            fontSize: 22,
            height: 1.2,
            fontWeight: FontWeight.w700,
            letterSpacing: -.5,
            color: AppColors.ink),
        headlineSmall: TextStyle(
            fontSize: 20,
            height: 1.25,
            fontWeight: FontWeight.w700,
            letterSpacing: -.4,
            color: AppColors.ink),
        titleLarge: TextStyle(
            fontSize: 17,
            height: 1.3,
            fontWeight: FontWeight.w700,
            letterSpacing: -.3,
            color: AppColors.ink),
        titleMedium: TextStyle(
            fontSize: 15,
            height: 1.3,
            fontWeight: FontWeight.w600,
            letterSpacing: -.2,
            color: AppColors.ink),
        titleSmall: TextStyle(
            fontSize: 14,
            height: 1.35,
            fontWeight: FontWeight.w600,
            letterSpacing: -.1,
            color: AppColors.ink),
        bodyLarge: TextStyle(
            fontSize: 15,
            height: 1.5,
            letterSpacing: -.2,
            color: AppColors.ink),
        bodyMedium: TextStyle(
            fontSize: 14,
            height: 1.45,
            letterSpacing: -.1,
            color: AppColors.ink),
        bodySmall:
            TextStyle(fontSize: 12.5, height: 1.4, color: AppColors.muted),
        labelLarge: TextStyle(
            fontSize: 14.5,
            fontWeight: FontWeight.w600,
            letterSpacing: -.1,
            color: AppColors.ink),
        labelMedium: TextStyle(
            fontSize: 12.5, fontWeight: FontWeight.w600, color: AppColors.ink),
        labelSmall: TextStyle(
            fontSize: 11,
            fontWeight: FontWeight.w700,
            letterSpacing: .5,
            color: AppColors.muted),
      ),
      // Charcoal bars with white type everywhere, as in the header of the
      // home screens. Sign-in screens opt back into a light bar.
      appBarTheme: const AppBarTheme(
        backgroundColor: AppColors.ink,
        foregroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        scrolledUnderElevation: 0,
        centerTitle: false,
        titleSpacing: 16,
        systemOverlayStyle: darkChrome,
        iconTheme: IconThemeData(color: Colors.white, size: 24),
        actionsIconTheme: IconThemeData(color: Colors.white, size: 24),
        titleTextStyle: TextStyle(
          fontFamily: fontFamily,
          fontSize: 17,
          fontWeight: FontWeight.w700,
          letterSpacing: -.3,
          color: Colors.white,
        ),
      ),
      cardTheme: const CardThemeData(
        color: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        margin: EdgeInsets.zero,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(10)),
          side: BorderSide(color: AppColors.border),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: AppColors.surface,
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        border: const OutlineInputBorder(
            borderRadius: _radius,
            borderSide: BorderSide(color: AppColors.border)),
        enabledBorder: const OutlineInputBorder(
            borderRadius: _radius,
            borderSide: BorderSide(color: AppColors.border)),
        disabledBorder: const OutlineInputBorder(
            borderRadius: _radius,
            borderSide: BorderSide(color: AppColors.fill)),
        focusedBorder: const OutlineInputBorder(
          borderRadius: _radius,
          borderSide: BorderSide(color: AppColors.brand, width: 1.4),
        ),
        errorBorder: const OutlineInputBorder(
          borderRadius: _radius,
          borderSide: BorderSide(color: AppColors.danger),
        ),
        focusedErrorBorder: const OutlineInputBorder(
          borderRadius: _radius,
          borderSide: BorderSide(color: AppColors.danger, width: 1.4),
        ),
        labelStyle: const TextStyle(color: AppColors.muted),
        floatingLabelStyle: const TextStyle(
            color: AppColors.brandText, fontWeight: FontWeight.w600),
        hintStyle: const TextStyle(color: AppColors.subtle),
        helperStyle: const TextStyle(color: AppColors.muted, fontSize: 12),
        errorStyle: const TextStyle(color: AppColors.danger, fontSize: 12),
        prefixIconColor: WidgetStateColor.resolveWith((states) =>
            states.contains(WidgetState.focused)
                ? AppColors.brand
                : AppColors.muted),
        suffixIconColor: AppColors.muted,
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: AppColors.brand,
          foregroundColor: Colors.white,
          disabledBackgroundColor: AppColors.border,
          disabledForegroundColor: AppColors.subtle,
          minimumSize: const Size(64, 52),
          padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 14),
          textStyle: buttonText,
          shape: const RoundedRectangleBorder(borderRadius: _radius),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: AppColors.ink,
          minimumSize: const Size(64, 52),
          padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 14),
          side: const BorderSide(color: AppColors.line),
          textStyle: buttonText,
          shape: const RoundedRectangleBorder(borderRadius: _radius),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: AppColors.brandText,
          textStyle: buttonText.copyWith(fontSize: 14),
          shape: const RoundedRectangleBorder(borderRadius: _radius),
        ),
      ),
      segmentedButtonTheme: SegmentedButtonThemeData(
        style: ButtonStyle(
          backgroundColor: WidgetStateColor.resolveWith((states) =>
              states.contains(WidgetState.selected)
                  ? AppColors.brandSoft
                  : AppColors.surface),
          foregroundColor: WidgetStateColor.resolveWith((states) =>
              states.contains(WidgetState.selected)
                  ? AppColors.brandText
                  : AppColors.ink),
          side: WidgetStateProperty.resolveWith((states) => BorderSide(
              color: states.contains(WidgetState.selected)
                  ? AppColors.brand
                  : AppColors.line)),
          shape: const WidgetStatePropertyAll(
              RoundedRectangleBorder(borderRadius: _radius)),
          textStyle: const WidgetStatePropertyAll(TextStyle(
              fontFamily: fontFamily,
              fontWeight: FontWeight.w600,
              fontSize: 13.5)),
          minimumSize: const WidgetStatePropertyAll(Size(0, 44)),
        ),
      ),
      chipTheme: const ChipThemeData(
        backgroundColor: AppColors.surface,
        selectedColor: AppColors.brandSoft,
        checkmarkColor: AppColors.brandText,
        side: BorderSide(color: AppColors.border),
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(6))),
        padding: EdgeInsets.symmetric(horizontal: 8),
        labelStyle: TextStyle(
            fontFamily: fontFamily,
            fontSize: 12.5,
            fontWeight: FontWeight.w600,
            color: AppColors.ink),
      ),
      tabBarTheme: const TabBarThemeData(
        labelColor: AppColors.brand,
        unselectedLabelColor: AppColors.muted,
        indicatorColor: AppColors.brand,
        indicatorSize: TabBarIndicatorSize.tab,
        dividerColor: AppColors.border,
        labelStyle: TextStyle(
            fontFamily: fontFamily, fontSize: 14, fontWeight: FontWeight.w700),
        unselectedLabelStyle: TextStyle(
            fontFamily: fontFamily, fontSize: 14, fontWeight: FontWeight.w500),
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        height: 64,
        indicatorColor: Colors.transparent,
        labelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
        iconTheme: WidgetStateProperty.resolveWith((states) => IconThemeData(
              size: 24,
              color: states.contains(WidgetState.selected)
                  ? AppColors.brand
                  : AppColors.muted,
            )),
        labelTextStyle: WidgetStateProperty.resolveWith((states) => TextStyle(
              fontFamily: fontFamily,
              fontSize: 11.5,
              fontWeight: states.contains(WidgetState.selected)
                  ? FontWeight.w700
                  : FontWeight.w500,
              color: states.contains(WidgetState.selected)
                  ? AppColors.brand
                  : AppColors.muted,
            )),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: AppColors.brand,
        foregroundColor: Colors.white,
        elevation: 2,
        focusElevation: 2,
        hoverElevation: 3,
        highlightElevation: 4,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(10))),
        extendedTextStyle: TextStyle(
            fontFamily: fontFamily,
            fontSize: 14.5,
            fontWeight: FontWeight.w700),
      ),
      dividerTheme:
          const DividerThemeData(color: AppColors.border, thickness: 1),
      listTileTheme: const ListTileThemeData(
        iconColor: AppColors.ink,
        contentPadding: EdgeInsets.symmetric(horizontal: 16),
      ),
      expansionTileTheme: const ExpansionTileThemeData(
        iconColor: AppColors.ink,
        collapsedIconColor: AppColors.muted,
        shape: Border(),
        collapsedShape: Border(),
      ),
      popupMenuTheme: const PopupMenuThemeData(
        color: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        elevation: 8,
        shadowColor: Color(0x33000000),
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(10))),
        textStyle: TextStyle(
            fontFamily: fontFamily,
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: AppColors.ink),
      ),
      snackBarTheme: const SnackBarThemeData(
        behavior: SnackBarBehavior.floating,
        backgroundColor: AppColors.ink,
        actionTextColor: AppColors.brand,
        elevation: 0,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(8))),
        contentTextStyle: TextStyle(
            fontFamily: fontFamily,
            color: Colors.white,
            fontSize: 13.5,
            fontWeight: FontWeight.w600),
      ),
      dialogTheme: const DialogThemeData(
        backgroundColor: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(14))),
        titleTextStyle: TextStyle(
            fontFamily: fontFamily,
            fontSize: 19,
            fontWeight: FontWeight.w800,
            letterSpacing: -.4,
            color: AppColors.ink),
        contentTextStyle: TextStyle(
            fontFamily: fontFamily,
            fontSize: 14,
            height: 1.45,
            color: AppColors.muted),
      ),
      bottomSheetTheme: const BottomSheetThemeData(
        backgroundColor: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        modalBackgroundColor: AppColors.surface,
        dragHandleColor: AppColors.line,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.vertical(top: Radius.circular(16))),
      ),
      datePickerTheme: const DatePickerThemeData(
        backgroundColor: AppColors.surface,
        surfaceTintColor: Colors.transparent,
        headerBackgroundColor: AppColors.ink,
        headerForegroundColor: Colors.white,
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(14))),
      ),
      tooltipTheme: const TooltipThemeData(
        decoration: BoxDecoration(
            color: AppColors.ink,
            borderRadius: BorderRadius.all(Radius.circular(6))),
        textStyle: TextStyle(
            fontFamily: fontFamily, color: Colors.white, fontSize: 12),
      ),
      progressIndicatorTheme: const ProgressIndicatorThemeData(
        color: AppColors.brand,
        linearTrackColor: AppColors.brandSoft,
        circularTrackColor: Colors.transparent,
      ),
    );
  }

  static ThemeData dark() {
    const scheme = ColorScheme.dark(
      primary: AppColors.brand,
      onPrimary: Colors.white,
      secondary: Colors.white,
      onSecondary: AppColors.ink,
      surface: Color(0xFF1F222D),
      onSurface: Color(0xFFF2F3F7),
      error: AppColors.danger,
    );
    return ThemeData(
      useMaterial3: true,
      colorScheme: scheme,
      fontFamily: fontFamily,
      scaffoldBackgroundColor: const Color(0xFF15171F),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF15171F),
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        systemOverlayStyle: darkChrome,
      ),
    );
  }
}
